version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: quickcrm-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QuickCRM@2024!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - quickcrm-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./Backend
      dockerfile: QuickCRM.API/Dockerfile
    container_name: quickcrm-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=QuickCRM;User Id=sa;Password=QuickCRM@2024!;TrustServerCertificate=true;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - quickcrm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: quickcrm-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - quickcrm-network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  quickcrm-network:
    driver: bridge
