[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet build --configuration Release --no-restore"]

[phases.start]
cmd = "dotnet run --project QuickCRM.API --configuration Release --no-build"
